Import popover component to use
shopware/meteor pull request #136
Opened 2024-04-15 05:35 UTC by nguyenquocdaile

## What?
The Popover component is already implemented in storybook `https://meteor-component-library.vercel.app/?path=/docs/components-overlay-mt-popover--docs`, but it's not imported to use here https://github.com/shopware/meteor/blob/main/packages/component-library/src/index.ts

2024-04-15 07:19 UTC, Haberkamp requested changes
Hey, thanks for the PR. Please add a changelog with a minor version bump. This way other devs will be aware of what changed. If you need help with that you can check out the contribution guidelines in the repository.

2024-04-15 07:47 UTC, nguyenquocdaile commented
> Hey, thanks for the PR. Please add a changelog with a minor version bump. This way other devs will be aware of what changed. If you need help with that you can check out the contribution guidelines in the repository.

Hi, I added it 😊

2024-04-15 14:22 UTC, Haberkamp approved these changes

2024-04-15 14:44 UTC, jleifeld requested changes
Would also export popover items. Otherwise the component can't be used correctly

2024-04-16 03:18 UTC, nguyenquocdaile commented
> Would also export popover items. Otherwise the component can't be used correctly

Yes, I also export popover-item-result too 😊

2024-04-17 07:55 UTC, jleifeld approved these changes

2024-04-17 07:56 UTC, merged