Add a prop to remove settings table button in the header
shopware/meteor pull request #138
Opened 2024-04-19 07:21 UTC by nguyenquocdaile

## What?
There are two issues in this PR 

1. If we set two props `disableEdit` and `disableDelete` is true. It will have a small bug UI 

<img width="379" alt="Screenshot 2024-04-19 at 11 15 00" src="https://github.com/shopware/meteor/assets/12345613/da8cab5d-994b-4e1e-b634-6b995e8d7ed1">

2. I add props to disable the settings table. And remove the last column when set three props `disableEdit`, `disableDelete`, `disableSettingsTable` are true.

2024-04-22 06:34 UTC, Haberkamp commented
@nguyenquocdaile hey good catch, one small thing. Instead of adding another prop I suggest that we hide the context menu button if both `disableEdit` and `disableDelete` are set to true trough a computed property.

2024-04-22 07:01 UTC, nguyenquocdaile commented
> @nguyenquocdaile hey good catch, one small thing. Instead of adding another prop I suggest that we hide the context menu button if both `disableEdit` and `disableDelete` are set to true trough a computed property.

Hi @Haberkamp, Another prop ( disableSettingsTable ) is to disable settings table here :D. it's not related to the context menu button.

![Screenshot 2024-04-22 at 13 57 10](https://github.com/shopware/meteor/assets/12345613/b490f7a1-a198-48ca-be08-2cd4e0671b10)



If a set three props `disableEdit`, `disableDelete`, `disableSettingsTable` is true. The last column will remove also.

2024-04-25 06:42 UTC, jleifeld requested changes
Looks also alright 🙂 Would be also cool to add a visual test to it to make sure we don't break it in the future

2024-04-25 12:18 UTC, jleifeld approved these changes

2024-04-25 13:34 UTC, merged