NEXT-35651 - add tokens to switch component
shopware/meteor pull request #156
Opened 2024-05-02 12:31 UTC by Haberkamp

## What?

I added token support for the switch component.

## Why?

This brings the component closer to the designs in Figma.

## How?

I replaced the SCSS variables with the design tokens.

## Testing?

You can check out the changes in the branch preview below.

2024-05-17 11:28 UTC, jleifeld requested changes

2024-05-17 11:28 UTC, jleifeld commented on packages/component-library/src/components/form/mt-switch/mt-switch.vue
> +      // TODO: what does this do?
missing todo

2024-05-17 12:45 UTC, seggewiss commented on packages/component-library/src/components/form/mt-switch/mt-switch.vue
> +      // TODO: what does this do?
We need the TODO rule everwhere :D

2024-05-21 07:38 UTC, jleifeld approved these changes

2024-05-21 07:38 UTC, merged