NEXT-35659 - add tokens for data table
shopware/meteor pull request #167
Opened 2024-05-13 09:18 UTC by Haberkamp

## What?

I added tokens for the data table component.

## Why?

This brings the component closer to the design system.

## How?

## Testing?

You can checkout the changes in the branch preview below.

## Anything Else?

2024-05-17 07:15 UTC, fabianhueske commented on packages/component-library/src/components/table-and-list/mt-data-table/mt-data-table.vue
> +      background: #fff;
```suggestion
      color: var(--color-text-secondary-default);
      background: var(--color-icon-inverted-default);
```

Maybe 🤷‍♂️ Depends on where this is applied 😄

2024-05-17 11:27 UTC, jleifeld requested changes

2024-05-17 11:27 UTC, jleifeld commented on packages/component-library/__snapshots__/interaction-tests-table-and-list-mt-data-table--visual-test-add-column-indicator-popover-snap.png
The contrast in the header is not given to the bar with search and buttons. Is this really wanted? In the screendesigns of the data table this contrast is wanted

2024-05-31 12:37 UTC, jleifeld approved these changes

2024-05-31 13:06 UTC, merged