Add Slider Component
shopware/meteor pull request #239
Opened 2024-07-16 14:17 UTC by Deristes

## What

Add slider component

## Why?

It is needed for future features.

## Screenshots
![image](https://github.com/user-attachments/assets/267279ca-f8cf-4a56-aa5a-c05b4fdf76d4)
![image](https://github.com/user-attachments/assets/d7f9fac3-887c-4aa7-80ca-92b41f56b9e3)

2024-07-19 07:27 UTC, dfrancos-hub approved these changes

2024-07-19 08:10 UTC, ffrank913 approved these changes

2024-07-22 14:30 UTC, Haberkamp requested changes
Please add a changelog. You can do that via `npx changeset`. If you need more information on how to do it you can check out the `CONTRIBUTING.md` file in this repository.

2024-07-24 09:15 UTC, Haberkamp approved these changes

2024-07-24 09:16 UTC, merged