fix: fully implement x-small mt-button size
shopware/meteor pull request #247
Opened 2024-07-29 19:20 UTC by bojanrajh

## What?

Allows `x-small` size for  `mt-button`.

## Why?

Validation for `size` prop failed, but the rest of CSS is there.

## How?

By allowing `x-small` and adding a story.

## Testing?

Storybook.

## Screenshots (optional)

## Anything Else?

2024-08-15 07:53 UTC, Haberkamp requested changes
Please add a changelog and update the visual tests

2024-08-20 07:26 UTC, Haberkamp commented on .changeset/new-buttons-join.md
> +Test coverage for x-small mt-button
I would re-write this to something that more user-facing like add x-small variant to button component or allow x-small as valid variant for button

2024-08-20 08:21 UTC, bojanrajh commented on .changeset/new-buttons-join.md
> +Test coverage for x-small mt-button
```suggestion
allow x-small as valid variant for button
```

2024-08-21 06:49 UTC, Haberkamp approved these changes

2024-08-21 06:51 UTC, merged