PS-337 - Allow toggling page smart bar
shopware/meteor pull request #255
Opened 2024-08-12 07:49 UTC by sydinh

## What?

Allow toggling page smart bar.

## Why?

Some modules need a wider view.

## How?

N/A

## Testing?

N/A

## Screenshots (optional)

N/A

## Anything Else?

2024-08-13 07:37 UTC, jleifeld requested changes

2024-08-13 07:37 UTC, jleifeld commented on docs/admin-sdk/docs/guide/2_api-reference/ui/mainModule.md
> +    ui.mainModule.hideSmartBar({});
Shouldn't it be possible to deactivate the bar using this property (`displaySearchBar`) ? https://developer.shopware.com/resources/admin-extension-sdk/api-reference/ui/mainModule.html#parameters

2024-08-13 08:12 UTC, jleifeld approved these changes

2024-09-16 09:33 UTC, nguyenquocdaile approved these changes

2024-09-16 09:34 UTC, vienthuong approved these changes

2024-09-17 06:51 UTC, jleifeld commented on .changeset/soft-chicken-applaud.md
> +"@shopware-ag/meteor-admin-sdk": patch
It is not a patch, it is a minor version update

2024-09-17 06:51 UTC, jleifeld commented on docs/admin-sdk/docs/guide/2_api-reference/ui/mainModule.md
> +### Hide smart bar
Add a information since which Shopware version this feature will work

2024-09-17 09:18 UTC, jleifeld approved these changes

2024-09-17 09:19 UTC, merged