Replace flatpickr
shopware/meteor pull request #344
Opened 2024-10-22 07:12 UTC by alastair-simon

## What?
Flatpickr replaced by vue 3 datepicker
## Why?
Needed to be updated to fit design system more closely 
## How?
Repalced flatpickr with vue 3 datepicker and updated styling
## Testing?
I've written some unit tests but feel free to take a look yourself

2024-10-30 12:59 UTC, Haberkamp requested changes
![Bildschirmfoto 2024-10-30 um 13 56 35](https://github.com/user-attachments/assets/c9412c58-789d-42a3-8f25-d79e8126dd24)

The arrow looks a bit weird.

![Bildschirmfoto 2024-10-30 um 13 59 12](https://github.com/user-attachments/assets/af8918e6-4056-4d46-b873-51e12086bf61)

There is only partial support for dark mode. Please make sure it fully supports dark mode, by adding tokens everywhere.

2024-10-30 12:59 UTC, Haberkamp commented on packages/component-library/package.json
> +    "@vuepic/vue-datepicker": "^9.0.3",
The flackpickr dependency can be removed.

2024-11-25 14:01 UTC, Haberkamp approved these changes

2024-11-25 14:01 UTC, Haberkamp commented on .github/workflows/visual-tests.yml
> -          "wait-on http://127.0.0.1:6006 && pnpx turbo run test:storybook --filter=@shopware-ag/meteor-component-library"
the -u flag needs to be removed.

2024-11-28 09:46 UTC, Lucsy3012 approved these changes

2024-12-12 08:26 UTC, closed without merging