NEXT-17726 - right align numbers in numbers field
shopware/meteor pull request #405
Opened 2024-11-29 13:25 UTC by jleifeld

## What?

Right align the numbers in the number field

## Screenshots (optional)

<img width="388" alt="Bildschirmfoto 2024-11-29 um 14 24 46" src="https://github.com/user-attachments/assets/fd376fdf-0495-4871-924b-7b58aee0877e">

2024-11-29 13:55 UTC, jleifeld commented
@Haberkamp do you know why the Visual Testing pipeline is not red?

2024-12-02 08:40 UTC, fabianhueske commented
Hi @jleifeld 😊 I would suggest to leave the default to left aligned and add a prop to switch to right alignment since right aligning number fields is perfect for some cases but only for same. We do have a lot more cases where left alignment fits better.

2024-12-03 07:25 UTC, jleifeld commented
> Hi @jleifeld 😊 I would suggest to leave the default to left aligned and add a prop to switch to right alignment since right aligning number fields is perfect for some cases but only for some. We do have a lot more cases where left alignment fits better.

Thanks for the feedback! I changed it 👍

2024-12-03 09:38 UTC, Haberkamp requested changes

2024-12-03 09:38 UTC, Haberkamp commented on packages/component-library/src/components/form/mt-number-field/mt-number-field.vue
> +}
I guess it makes sense to only use `.mt-number-field__align-end` as the selector as the extra scoping to `.mt-number-field` is unnecessary. It's already included in the longer selector.

2024-12-03 12:14 UTC, Haberkamp approved these changes

2024-12-03 13:02 UTC, seggewiss approved these changes

2024-12-03 13:11 UTC, merged