Add rule for font tokens
shopware/meteor pull request #406
Opened 2024-11-29 15:40 UTC by alastair-simon

## What?
This rule checks every font value and reports violations.

## Why?
To catch incorrect or improper uses of fonts 

## How?
The rule goes over each individual value and reports any violations.

## Testing?
I've written a few tests to check the rule works as expected

2024-12-03 12:31 UTC, Haberkamp requested changes
The rule also must be inside the array of the `src/index.ts` file. Otherwise other projects cannot use the rule. And another thing: Could you enable the rule in the `.stylelintrc.json` file for the component library and set it's severity to warning? That way we can see if the missed something in meteor itself.

2024-12-03 12:50 UTC, Lucsy3012 submitted a review, later dismissed

2024-12-05 10:10 UTC, Haberkamp requested changes

2024-12-05 11:12 UTC, alastair-simon commented on packages/stylelint-plugin-meteor/src/rules/prefer-font-token/prefer-font-token.test.ts
> +    { code: ".a { font-size: inherit; }" },
done

2024-12-05 11:12 UTC, alastair-simon commented on packages/stylelint-plugin-meteor/src/rules/prefer-font-token/index.ts
> +  rejected: (value) => `Font property must use token, got "${value}"`,
done

2024-12-06 09:33 UTC, Haberkamp approved these changes

2024-12-06 10:02 UTC, Haberkamp approved these changes

2024-12-06 10:02 UTC, merged