feat: add developer-portal workflows
shopware/meteor pull request #51
Opened 2024-02-21 10:30 UTC by bojanrajh

## What?
3 new workflows for communicating with the DevHub:
 - `developer-portal-healthcheck` - triggers a new [preview build](https://github.com/shopware/developer-portal/blob/main/.github/workflows/external-healthcheck.yml) in `developer-portal` for every PR targeting `main` branch in this repo
 - `update-healthcheck` - needed to update the PR status check from the previous workflow - will be replaced with a dedicated GitHub app to avoid usage of the PAT
 - `deploy-developer-portal` - triggers a new [production build](https://github.com/shopware/developer-portal/blob/main/.github/workflows/checkout-test-build-deploy.yml) in `developer-portal` whenever the `main` branch has changed

## Why?
So we can automate DevHub actions.

## How?
By adding a few workflows.

## Testing?
Already used by `shopware/docs`, `shopware/frontends`, `shopware/release-notes`.

## Screenshots (optional)

## Anything Else?

2024-02-21 15:12 UTC, Haberkamp requested changes
One workflow seems to be broken.

2024-02-21 15:12 UTC, Haberkamp commented on .gitignore
> +.idea
I know a bit nit picky. Could you do that in a separate commit?

2024-02-21 15:22 UTC, bojanrajh commented
> One workflow seems to be broken.

It will work once the `DEV_HUB_PERSONAL_ACCESS_TOKEN` secret is set.

2024-02-26 09:24 UTC, Haberkamp requested changes

2024-02-26 09:24 UTC, Haberkamp commented on .github/workflows/developer-portal-healthcheck.yml
> +  create-healthcheck:
I would rename this workflow and job to something that tells me this job creates a preview build. I understand a healthcheck as an Rest endpoint that you ping and you get a response back that the system is running without any issues.

2024-02-26 09:24 UTC, Haberkamp commented on .github/workflows/update-healthcheck.yml
> +name: Update healthcheck
Here the same as above. I would rename this to something like "Update developer portal preview"

2025-02-19 11:56 UTC, bojanrajh commented
This PR is not needed with new `DevHub connector` GitHub app, therefore I'm closing it.

2025-02-19 11:56 UTC, closed without merging