Add nuxt example app
shopware/meteor pull request #96
Opened 2024-03-15 09:04 UTC by Haberkamp

## What?

I added a Nuxt SSR example project.

## Why?

This helps us to see wether or not our examples are SSR compatible.

## How?

I added a new project.

## Testing?

There is an integration test to see if the application is working correctly.

## Anything Else?

There are several more things I did:
1. I added the `examples/` directory to the readme of the project
2. I included the tokens in the global css file for the meteor components
3. I fixed the import path in the readme of the token project

2024-03-21 14:53 UTC, seggewiss commented on examples/nuxt-app/playwright.config.ts
> +    /* Test against mobile viewports. */
Can these comments go?

2024-03-21 14:55 UTC, jleifeld requested changes
Looks good. I would also add a screenshot test (natively supported in Playwright) to make sure that the component rendering works correctly: https://playwright.dev/docs/test-snapshots

Then we see if we mess up with CSS and other stuff

2024-03-21 14:56 UTC, Haberkamp commented on examples/nuxt-app/playwright.config.ts
> +    /* Test against mobile viewports. */
Sure!

2024-03-21 15:49 UTC, seggewiss approved these changes

2024-03-22 08:06 UTC, jleifeld approved these changes

2024-03-22 08:25 UTC, merged